import { MD3LightTheme, configureFonts, type MD3Theme } from 'react-native-paper';

const fontConfig = {
  displayLarge: {
    fontFamily: 'System',
    fontSize: 36,
    fontWeight: '700' as const,
    letterSpacing: 0,
    lineHeight: 44,
  },
  displayMedium: {
    fontFamily: 'System',
    fontSize: 30,
    fontWeight: '700' as const,
    letterSpacing: 0,
    lineHeight: 38,
  },
  headlineLarge: {
    fontFamily: 'System',
    fontSize: 26,
    fontWeight: '600' as const,
    letterSpacing: 0,
    lineHeight: 32,
  },
  headlineMedium: {
    fontFamily: 'System',
    fontSize: 22,
    fontWeight: '600' as const,
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleLarge: {
    fontFamily: 'System',
    fontSize: 20,
    fontWeight: '600' as const,
    letterSpacing: 0.15,
    lineHeight: 26,
  },
  titleMedium: {
    fontFamily: 'System',
    fontSize: 18,
    fontWeight: '600' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  bodyLarge: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '400' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '400' as const,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  labelLarge: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '600' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
};

export const appTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 14,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3LightTheme.colors,
    primary: '#5B5FEF',
    onPrimary: '#FFFFFF',
    primaryContainer: '#E4E5FF',
    onPrimaryContainer: '#161855',
    secondary: '#0EA5E9',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#D8F1FD',
    onSecondaryContainer: '#003547',
    tertiary: '#8B5CF6',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#EDE9FE',
    onTertiaryContainer: '#2E1065',
    error: '#DC2626',
    onError: '#FFFFFF',
    errorContainer: '#FEE2E2',
    onErrorContainer: '#450A0A',
    background: '#F4F6FB',
    onBackground: '#0F172A',
    surface: '#FFFFFF',
    onSurface: '#0F172A',
    surfaceVariant: '#E8ECF4',
    onSurfaceVariant: '#475569',
    outline: '#CBD5E1',
    outlineVariant: '#E2E8F0',
    surfaceDisabled: 'rgba(15, 23, 42, 0.08)',
    onSurfaceDisabled: 'rgba(15, 23, 42, 0.38)',
    backdrop: 'rgba(15, 23, 42, 0.45)',
  },
};
